apiVersion: apps/v1
kind: Deployment
metadata:
  name: microinquilino-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: microinquilino
  replicas: 2
  template:
    metadata:
      labels:
        app: microinquilino
    spec:
        containers:
          - name: microinquilino
            image: gcr.io/projetoptiptr-307918/microinquilino:v1

--- 
#Service
apiVersion: v1
kind: Service
metadata:
  name: microinquilino-service
spec:
  selector:
    app: microinquilino
  type: ClusterIP
  ports:
    - name: http
      port: 8081